seed_everything: true

trainer:
  logger: true
  accelerator: gpu
  devices: 0
  val_check_interval: 2000
  limit_val_batches: 200
  log_every_n_steps: 15
  max_epochs: 30
  enable_checkpointing: true
  enable_progress_bar: true
  inference_mode: false
  gradient_clip_val: 0.1
  gradient_clip_algorithm: value
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: train/loss
        filename: best_train_loss
        save_weights_only: true
        every_n_train_steps: 
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        filename: best_val_loss
        save_weights_only: true
        every_n_epochs: 1
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/cider
        filename: best_val_cider
        save_weights_only: true
        every_n_epochs: 1
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: model
        every_n_epochs: 1
        save_on_train_epoch_end: true

data:
  class_path: data.modules.coco.COCODataModule
  init_args:
    input_json: data/dataset_coco.json
    image_root: data/images
    bottomup_root: data/bu_data
    output_json: data/cocotalk.json
    output_pkl: data/coco-all
    bu_data: data/cocobu
    image_feature: att
    box_feature: box
    # input_rel_box_dir: cocobu_box_relative
    # input_grid_vec_dir: cocobu_box_vec
    # input_label_h5: coco_label.h5
    normalize_image_feature: false
    normalize_box: false
    captions_per_image: 5
    max_caption_length: 16
    min_word_frequency: 5
    batch_size: 16
    num_workers: 2

checkpoint: checkpoints
logs: logs
